### ISSUE TITLE
ERROR in Metadata version mismatch for module node_modules/stripe-angular/index.d.ts

### ISSUE THREAD

**Issue by tariq-firoz** [AckerApple/stripe-angular#1]
ERROR in Metadata version mismatch for module node_modules/stripe-angular/index.d.ts

**Comment by AckerApple** [comment]
Are you using Angular4? I’ve seen that error when Angular changed so much that even modules become incompatible if not on same version.

Tell me your exact Angular core package version number, please.

This package works with Angular 5 and 6 for sure. Had to bet, I’d bet you on Angular 4

**Comment by AckerApple** [comment]
This package has been upgraded to support Ivy. Some issues were resolved that I think may help this old issue ticket out. Pull request #16 fixes a lot for build errors. Try new 0.6.1 version of stripe-angular.


Be well.
