### ISSUE TITLE
0.5.0 not compatible with Angular 7

### ISSUE THREAD

**Issue by KennyGScott** [AckerApple/stripe-angular#12]
This may be a known issue, but there is nothing about it in your documentation. `ɵɵdefineInjectable()` is not a function in Angular 7. Angular 7 still requires `defineInjectable()` which of course is deprecated in Angular 8. Installing 0.4.1 solved the issue, but naturally would like to have the latest version.

**Comment by AckerApple** [comment]
Thank you for providing this information as I’m certain if true, it will affect others.

At this time i will not be taking any action.

**Comment by AckerApple** [comment]
@SudharakaP

When you recently test 0.5.0 were you using Angular 8 or older?

I was wondering if you ran into any issues as reported in this issue report

**Comment by SudharakaP** [comment]
@AckerApple : I am using Angular 8.0.0. We recently upgraded to Angular
8.0.0 and as soon as we upgraded we had this exact same issue where the
production build failed. It took me sometime to figure that it's this
package that was causing it. 😊

**Comment by AckerApple** [comment]
Thank you so much. It would appear this package now requires ng v8 or greater.

**Comment by SudharakaP** [comment]
@AckerApple : You mean it doesn't have backward compatibility anymore ?

**Comment by AckerApple** [comment]
Based on this issue report and your findings as well I am to conclude that is the truth. I have not confirmed for myself but when Angular changes major versions that possibility of breaking compatibility is there. Not the first time this has occurred especially ng 2-5

**Comment by SudharakaP** [comment]
@AckerApple : I am sorry, I think I was confused here; I was reading all the messages above and replying to them via email. The first message I got was your first comment on this issue that mentions my name I thought this is issue; https://github.com/AckerApple/stripe-angular/issues/9.

Now when I opened this in the computer I see that this is a different issue. I should clarify; that I didn't experience this issue when I upgraded to Angular 8.0.0. The only issue I faced was the one I fixed. 

Sorry for the confusion. :(

**Comment by SudharakaP** [comment]
@AckerApple : I am putting up a CI server for our project (which is open source) this week; and after that is done you'll see for yourself that there are no build errors.

**Comment by AckerApple** [comment]
The build errors only seem to occur when you build on less than 8. Angular 8 will work because it’s what this package is built on. However again, I’ve not seen this error for myself

Thank you for the follow up. Being that no one else has confirmed this issue, I’ll still hold off until someone else confirms it’s an issue

**Comment by SudharakaP** [comment]
@AckerApple : We might need a readme update (https://github.com/AckerApple/stripe-angular/pull/13) ?

**Comment by KennyGScott** [comment]
Thanks for looking into this @AckerApple and thank you @SudharakaP for you input as well. Much appreciated!

**Comment by dobobaie** [comment]
Same issue for me with Angular 6.x. @SudharakaP 👍

**Comment by neil-119** [comment]
We're seeing the same issue with Angular 7.

**Comment by AckerApple** [comment]
Pull reqeust #16 made this package compatible with Ivy. There is no plan to go back and support older versions.

This ticket will be closed next time I clean up my repos.
