### ISSUE TITLE
New Payment Intents API for SCA

### ISSUE THREAD

**Issue by fabiovasini** [AckerApple/stripe-angular#17]
Starting from September 2019, the Strong Customer Authentication (SCA) will require businesses in Europe to request additional authentication for online payments.

Does this package supports the Payment Intents API instead of the Charges API?

https://stripe.com/docs/payments/payment-intents/web

**Comment by anteAdamovic** [comment]
Will this package support the new payment intents ? Or is it deprecated ?

**Comment by AckerApple** [comment]
I created this package out of need. I don’t need this package anymore. Someone would need to issue a pull request for anything new that isn’t in this package.

**Comment by AckerApple** [comment]
I have picked this project back up again out of need and just released a major update.

This package supports Payment Methods and Sources which can be used in Pay Intents
