### ISSUE TITLE
How do i apply options or style to the card .

### ISSUE THREAD

**Issue by vinitzanje-analogyplus** [AckerApple/stripe-angular#2]
i want to use hidePostalCode , but there is no clear documentation of it .

**Comment by AckerApple** [comment]
hidePostalCode and all other options can be read about here: 

https://stripe.com/docs/stripe-js/reference#collecting-bank-account-details

This package, stripe-angular, is just a wrapper for Stripe for Angular

**Comment by oper2000** [comment]
Same here.
I understand what you are saying.
if you only can point me using your wrapper, how to get a reference to "card Element", so I can use the card. hidePostalCode = true
Thx

**Comment by AckerApple** [comment]
The main card component, can be reviewed here:
https://github.com/AckerApple/stripe-angular/blob/master/src/components/StripeCard.component.ts

**Comment by SudharakaP** [comment]
@oper2000 : Just as a quick example to change the font size; on your html stripe card; 

`<stripe-card [options]='getStyles()' #stripeCard ...... >`

and on your component you can write the function,

 ```
getStyles(): any {
        return {
            style: {
                base: {
                    fontSize: '16px'
                }
            }
        };
    }
```
