### ISSUE TITLE
Feature Request: Simplify Module Initialization

### ISSUE THREAD

**Issue by wSedlacek** [AckerApple/stripe-angular#22]
First off I would like to thank you for all your hard word on making this project. I have been looking for a Stripe solution for Angular for a while and this has come by far the closest to what I wanted.

It does seem like getting Stripe to work is a little bit tricky due to having to rely on Stipe Elements and the API it exposes thus making the setup cumbersome in a framework like Angular where if we had direct access to APIs it would make the process a lot easier on us.

That being said you have gotten by far the closest. I have one simple request to clean up my code a bit. That would be:
1) Export directly as `StripeModule` rather then `Module` so I don't have to rename the import.
2) Take in an option for the `publishable key` for the `forRoot()` initialization so I don't have to add `setPublishableKey()` to my App component.

Example of request:
`app.module.ts`
```ts
...
import { StripeModule } from 'stripe-angular';

@NgModule({
  imports: [StripeModule.forRoot(environment.stripe.pk), ...]
  ...
})
export class AppModule {}
```

These may seem like small things however I think it is small things like that that really make some libraries stand apart from others.

These changes don't have to replace the existing exports, that way not to be an immediate breaking change but instead could be added in then the old export of `Module` could be deprecated and removed later down the road similar to what Angular core does with deprecated APIs on major releases.

Beyond this my only other complaint would be having to use the options in order to apply CSS, however I know that isn't on you but instead on how Stripe has exposed their APIs to us.

Thank you so much for your time and hard work! I look forward to seeing how this Library progresses in 2020

**Comment by AckerApple** [comment]
Thank you. I’ll be short: if your willing to write all that, then you should be more than willing to issue a pull request for your desired changes.

I’m just one guy. Haven’t had to change this code in quite a while.

I won’t be making your change requests, you have to do the work and then I will publish your work

**Comment by wSedlacek** [comment]
I'm happy to write a pull request. I just wasn't sure if there was a specific reason this wasn't done already. Given your response it seems like there isn't. I'll get back to you once the pull request is ready to review.

Thank you very much for your quick response and time in reviewing my request.
