### ISSUE TITLE
Ad-block

### ISSUE THREAD

**Issue by Rui90** [AckerApple/stripe-angular#39]
Does this work with ad-block?

Because I tried to setup stripe on my own and I'm getting a bunch of Http Client errors because of ad block.

In this particular case, u-block origin.

**Comment by AckerApple** [comment]
I’d like to know how far you do and don’t get with this issue.

Stripe makes you render your credit card layout by external import via connections to their own display generation. This angular package just makes that process easier to engage, it’s a wrapper so you will most likely find exact same issues.

Stripe has a very interesting opinionated approach to ensure security and I’ve been fine with it for all my uses. Perhaps they have display alternative that would not be ad blocked like maybe I frame versus JavaScript injection idk haven’t gone down those roads
