### ISSUE TITLE
Facing error like Stripe PublishableKey NOT SET. Use method StripeScriptTag.setPublishableKey()

### ISSUE THREAD

**Issue by Hrddk** [AckerApple/stripe-angular#4]
I'm trying to add stripe-angular plugin to my application. below is my code. but facing error. please let me know is this code enough for you to point out what's going wrong?

- app.module.ts file

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { AppRoutingModule } from 'src/app/app-routing.module';
import { Module as StripeModule } from 'stripe-angular';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    NoopAnimationsModule,
	StripeModule
  ],
  providers: [],
  bootstrap: [AppComponent],

})
export class AppModule { }
```

- app.component.ts file
```
import { Component, OnInit } from '@angular/core';
import { StripeScriptTag } from 'stripe-angular';

@Component({
  selector: 'my-app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit, OnDestroy {
  constructor(private stripeScriptTag: StripeScriptTag) {
    stripeScriptTag.setPublishableKey('pk_live_***************************');
  }

  ngOnInit() {
  }

  onStripeInvalid(error: Error) {
    console.log('Validation Error', error);
  }

  setStripeToken(token: StripeToken) {
    console.log('Stripe token', token);
  }

  onStripeError(error: Error) {
    console.error('Stripe error', error);
  }
}
```

- app.component.html file
```
<stripe-card #stripeCard
  (catch)="onStripeError($event)"
  [(invalid)]="invalidError"
  (tokenChange)="setStripeToken($event)"
></stripe-card>

<button type="button" (click)="stripeCard.createToken(extraData)">createToken</button>
```

**Comment by AckerApple** [comment]
Which version of Angular you using?

When I see these old declarations like ‘implements OnInit, OnDestroy ’ it makes me thing you are all the way back on an older Angular

Also then I judge your github account and it seems new and with only sample start up code. Soo I’m left you think you may have something incompatible or just generally setup incorrectly

This package was built on Angular 6 or 7 and is used in production.

Keep trying, it works. Do you use npm to install your packages and did you install this package from npm. 

Extra check the basics and report back

**Comment by Hrddk** [comment]
I'm using angular version 6.
Yes, I'm using npm to install this package to my application.

**Comment by AckerApple** [comment]
I'll get back to you in time

**Comment by AckerApple** [comment]
Please review the following code but let me explain first.

For the package to talk with Stripe, a javascript script tag must be put onto the DOM. The javascript src is targeted at "https://js.stripe.com/v3/"

Your project must be within a browser and have the ability to access the aboved mentioned url

For all the above to happen, the following code is executed: https://github.com/AckerApple/stripe-angular/blob/master/src/StripeScriptTag.ts#L29


Please review the code and tell me if you think that code would execute for you (aka will a dynamic script tag work for your code)

**Comment by AckerApple** [comment]
Please uninstall and install version 0.2.3

While reviewing the code for you, I saw a potential issue. Hopefully it fixes what you were encountering but no guarantees

I still think it might be related to the environment that you are in with regards to dynamically requesting a javascript file

**Comment by Hrddk** [comment]
Thanks you very much for the update. let me give a try to this.

**Comment by AckerApple** [comment]
When you get this issue, does the console log in the browser give you any clues?

Trying to find what’s different about your configuration.

Any chance you could share your code as a repository I could checkout?

**Comment by Hrddk** [comment]
:) C(o_O)L

**Comment by AckerApple** [comment]
You were right all along. It was a loading sequencing issue. I found the issue when I setup a repository from scratch for us.

Thank you for your persistence and helping make this a better package.

Please acquire v0.2.4 and I bet you will be fine.

Let me know

**Comment by Hrddk** [comment]
It's sad but now I'm getting different error.
[https://www.dropbox.com/s/v7p2y8ypu5yu2ma/Capture.PNG?dl=0](url)

**Comment by AckerApple** [comment]
I have posted my testing branch. Everything works fine. Please try my branch to compare with what you've got going on.

https://github.com/AckerApple/stripe-angular/tree/try

```
git clone https://github.com/ackerapple/stripe-angular -b try
cd stripe-angular
npm install
npm start
```

**Comment by AckerApple** [comment]
Please acquire version 0.3.0 which now supports loadChildren lazy loading

Your NgModule injection statement must change on your base app to have `.forRoot()`

Please see the documentation here for module injection of stripe-angular: https://github.com/AckerApple/stripe-angular#inject

**Comment by Hrddk** [comment]
OK. I'll update you very soon. Thanks

**Comment by Hrddk** [comment]
Hey @AckerApple 
now everything is working fine in my application.
Thank you very much for the support. 👍  :)

**Comment by AckerApple** [comment]
Alright! That is so music to my ears. Quite the Friday maker. I super appreciate you sticking with this package while we figured it out.

It just so happened this week I needed lazy loading in my own application and I saw the issues more clearly. Great timing of sorts that I could resolve this issue.

Special request, now that I have solved your issue. Please consider a legit icon for you Github profile for several various reason. Top number one reason, I would simply like to remember those I work with. Think it over, will be great to see you again.

Again, thank you extra kindly for participating

**Comment by Hrddk** [comment]
How can I do that?

**Comment by AckerApple** [comment]
https://github.com/settings/profile

Look for upload new picture. But since you have no picture the view maybe different for your first profile photo upload

**Comment by AckerApple** [comment]
Really good to be seeing you, new friend. You can contact me on this package, any other package of mine, or if you need something like a recommendation.
