### ISSUE TITLE
StripeToken Error

### ISSUE THREAD

**Issue by Ahsanmughal** [AckerApple/stripe-angular#40]
Hi Acker, I am trying to use this package, but getting this error stripe-angular has no exported member 'StripeToken'.
import { StripeToken, StripeSource } from "stripe-angular";

Also got confuse with this 

Operations are preformed on construction
1) Checking for window.Stripe
2) If undefined, head tag is found and script tag with src "https://js.stripe.com/v3/" is added
3) Seting publishableKey in StripeJs library
4) All stripe-angular components use the initialized Stripe instance

Please provide details about this.
How can we use this package properly,

Thanks for your effort.

**Comment by AckerApple** [comment]
Message received. I will get back within 3 days with work or answers. 

Ping me if heard nothing by then. I just did major updates. If imports not working now for some reason than direct import most likely needed (aka use full path to file instead of index.ts alias)

**Comment by AckerApple** [comment]
I have pushed 1.4.2 aimed at addressing your callouts
