### ISSUE TITLE
Doesn't work with Angular SSR

### ISSUE THREAD

**Issue by mbagiella** [AckerApple/stripe-angular#41]
ReferenceError: window is not defined

**Comment by AckerApple** [comment]
You’ll most likely need to make a pull request against this file:

https://github.com/AckerApple/stripe-angular/blob/development/src/StripeScriptTag.ts#L50

**Comment by AckerApple** [comment]
I've made some recent major updates. Are you still wanting and in need of this change?

I can try to catch it in my next round of changes.

**Comment by selected-pixel-jameson** [comment]
I'm going to be implementing this with SSR today. I will let you know if it seems to be working or not.

**Comment by AckerApple** [comment]
@selected-pixel-jameson please do. I have been hella busy

**Comment by selected-pixel-jameson** [comment]
@AckerApple Sorry, I won't be using this library as it doesn't support some basic functionality such as the ability to style the ElementJS html elements. There appears to be a pull request for this, but it has not been merged. I will be using ngx-stripe instead.

**Comment by AckerApple** [comment]
I merged and published as 1.6.0 for other changes.

I reviewed what it would take to remove loading Stripe via javascript file and at this time I cannot afford the time to make happen.

**Comment by yroc92** [comment]
I am running into this as well. I think this might be as simple as replacing all references to `window` to instead inject the document token and then use `document.defaultView` in place of `window`. For example, in `StripeScriptTag.ts`, the constructor would include

```
import { DOCUMENT } from '@angular/common';
...
private window;

constructor(@Inject(DOCUMENT) private document: Document) {
        this.window = this.document.defaultView;
}
```
and then you would use `this.window` instead of `window` throughout your service and elsewhere.

**Comment by AckerApple** [comment]
@yroc92 I very much understand your call out. I have been using this package more and more but not for server side.

I will eventually get to this but @yroc92 if you are able to make a PR for this is would be most appreciated.

The work needs to be done to this exact file in this exact branch:
https://github.com/AckerApple/stripe-angular/blob/development/src/StripeScriptTag.ts

**Comment by AckerApple** [comment]
1.7.0 has been released to support server side rendering
