### ISSUE TITLE
Support passing in async method to StripeModule.forRoot

### ISSUE THREAD

**Issue by yringler** [AckerApple/stripe-angular#42]
It would be great if I could fetch the key from an API, and then use that in the service, instead of hard-coding.
Is that something you'd accept a PR for? I might take a shot at it if interested.

I think it should be relatively straight forward, because access to stripes API is through a promise, anyway.

**Comment by AckerApple** [comment]
i bet we support that just not documented and most likely not in the cleanest of ways

We have a file of [/src/StripeScriptTag.ts](https://github.com/AckerApple/stripe-angular/blob/master/src/StripeScriptTag.ts) that governs the loading of Stripe

I bet if you used for root with empty string keys and then loaded the StripeScriptTag.ts via dependency injection, you could then set the values async

Do you follow? If you are able to confirm, we can document it and make it better

**Comment by yringler** [comment]
Clear as :droplet:.
And it works! opened PR to document.
It's not the most graceful, but not terrible.

**Comment by AckerApple** [comment]
Thank you kindly. I am off until Monday and then I will merge and publish.

This project recently became heavily active again. Please do continue to pitch in as I have a few message from people saying in the end this project is better than the more popular one.

**Comment by yringler** [comment]
Possibly, especially if my client actually ends up using the site I'm working on.
Something to consider is adding more complete typing to the stripe instance. For example, I'm using
```typescript
(stripe as any).redirectToCheckout({
  sessionId: response.id
});
```
What about using the [definitelytyped typings](https://www.npmjs.com/package/@types/stripe-v3)?

**Comment by AckerApple** [comment]
I will merge and publish this tomorrow

**Comment by AckerApple** [comment]
When I published this I moved you from "Recipes" into a reformatted version labeled "Inject Async"
