### ISSUE TITLE
Must add @types/stripe-v3 in order to build

### ISSUE THREAD

**Issue by yringler** [AckerApple/stripe-angular#47]
I observed in my project that I got tons of type errors (from stripe-angular), because stripe types weren't found.
After I installed @types/stripe-v3, everything worked.
I think it's enough to document in the README that you also have to add @types/stripe-v3
Is there a better way to do that? Ideally stripe-angular would also export those types, generated during build, or have a way to automatically ensure that @types/stripe-v3 is installed. Maybe a peer dependency?

**Comment by AckerApple** [comment]
In this PR, Stripe types were added as if Stripe was a global instance. I let it fly thinking I’d just address impact if any calls outs were made

we have two choices as I see it:
- add the types install in some manner as described in the main description of these docs
- Or we replace global references with the typings in the stripe package itself

I am activity working on this project and will attempt to resolve this matter myself today

**Comment by yringler** [comment]
:hand:  That's me!
> I let it fly thinking I’d just address impact if any calls outs were made as impact perceived very small

My thoughts exactly

> the typings in the stripe package 

The typings in [stripe](https://www.npmjs.com/package/stripe) are for server.
There is [stripe-js](https://www.npmjs.com/package/@stripe/stripe-js), also [official](https://github.com/stripe/stripe-js)
From stripe-js:
> This package includes TypeScript declarations for Stripe.js

So it might be the same problem.

There has to be some way to include the types in the build...

**Comment by AckerApple** [comment]
Just released version 1.5.2 aimed at fixing this issue.

The readme and peerDependencies describe the need to install the stripe types.

Please verify for me

**Comment by yringler** [comment]
Great! When types weren't installed, I got a warning (missing peer dependency), I installed and everything worked.
