### ISSUE TITLE
Stripe-angular demo code is deprecated

### ISSUE THREAD

**Issue by callistachang** [AckerApple/stripe-angular#50]
Clicking the link "demo code on github" on https://ackerapple.github.io/stripe-angular/ leads to a 404 error. Is this code still available?
Thank you for your hard work on the package.

**Comment by AckerApple** [comment]
Thank you , that link needs to be updated to point to here:

https://github.com/AckerApple/stripe-angular/blob/gh-pages/src/components/app.component.ts

**Comment by AckerApple** [comment]
this has been fixed
