### ISSUE TITLE
Duplicate identifier 'ɵfac'

### ISSUE THREAD

**Issue by db-ruslan** [AckerApple/stripe-angular#53]
Error: node_modules/stripe-angular/components/StripeCard.component.d.ts:26:12 - error TS2300: Duplicate identifier 'ɵfac'.

26     static ɵfac: ɵngcc0.ɵɵFactoryDeclaration<StripeCard, never>;
              ~~~~


Error: node_modules/stripe-angular/components/StripeComponent.d.ts:17:12 - error TS2300: Duplicate identifier 'ɵfac'.

17     static ɵfac: ɵngcc0.ɵɵFactoryDeclaration<StripeComponent, never>;
              ~~~~

"@types/stripe-v3": "^3.1.28",
"stripe-angular": "^1.9.1",

**Comment by AckerApple** [comment]
Ok issue confirmed. Working at it now.

**Comment by AckerApple** [comment]
Please install `1.9.3` and issue should resolve. Please resolve this ticket if fixed for you then.

`npm install stripe-angular@1.9.3 --save-dev`
