### ISSUE TITLE
Library works in angular v15? 

### ISSUE THREAD

**Issue by aristotekean** [AckerApple/stripe-angular#55]
Hi, I install the library in angular 15 and do the following:

1. I put the https://js.stripe.com/v3/ inside index.html
2. Imported StripeModule.forRoot("") and write de pk inside 
3. Copied the next code from the docs
`import { Component } from "@angular/core"

const template=
`
<div *ngIf="invalidError" style="color:red">
  {{ invalidError.message }}
</div>

<stripe-card #stripeCard
  (catch) = "onStripeError($event)"
  [(complete)] = "cardDetailsFilledOut"
  [(invalid)] = "invalidError"
  (cardMounted) = "cardCaptureReady = 1"
  (paymentMethodChange) = "setPaymentMethod($event)"
  (tokenChange) = "setStripeToken($event)"
  (sourceChange) = "setStripeSource($event)"
></stripe-card>

<button type="button" (click)="stripeCard.createPaymentMethod(extraData)">createPaymentMethod</button>
<button type="button" (click)="stripeCard.createSource(extraData)">createSource</button>
<button type="button" (click)="stripeCard.createToken(extraData)">createToken</button>
**... more code**
``

And the example code not work, all erros said the same

<img width="789" alt="image" src="https://user-images.githubusercontent.com/12689339/231126264-e93e06e4-a5e5-4792-97e0-0018552f53ae.png">

**Comment by AckerApple** [comment]
Did what you are doing work with previous versions of Angular because your steps seem wrong.

read the install and usage docs. The one thing I’m pretty sure you have wrong is that you are manually including Stripe however that’s not needed and so I think Stripe is being imported twice

**Comment by aristotekean** [comment]
Was a development environment error, I deleted the stripe cdn script from the index and works, thanks you for your work and answer.
